services:
    backend:
        build:
            context: ./api
            dockerfile: api/Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./api:/var/www
            - E:/project/Todo_web_application/api/nginx.conf:/etc/nginx/nginx.conf  # Mount nginx.conf here
            - E:/project/Todo_web_application/api/.env:/var/www/.env                  # Mount .env file
        ports:
            - "8000:9000"
        depends_on:
            - db


    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todo_data
            MYSQL_USER: laravel
            MYSQL_PASSWORD:
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
